installer: load efi_gop and efi_uga in GRUB
Fixes the following:

> error: no suitable video mode found.
> Booting in blind mode

GOP is the Graphics Output Protocol, and UGA is the Universal Graphics
Adapter protocol, which was the equivalent of GOP in the days before
UEFI.  As far as I can tell, this was only ever implemented by some
very old Macs (the Ubuntu wiki says pre-2008[1]), but some pre-2008
Macs do support VT-x, so we probably should include efi_uga for them.

[1]: https://help.ubuntu.com/community/UEFIBooting#Apple_Mac_EFI_systems-1